---
 - hosts: control
   become: true
   tasks:
           - name: grub_cfg permission
             file:
                       path: /boot/grub2/grub.cfg
                       owner: root
                       group: root
                       mode: 0000
           - name: grubenv premission
             file:
                       path: /boot/grub2/grubenv
                       owner: root
                       group: root
                       mode: 0000

