---
 - hosts: control
   become: true
   tasks:
           - name: list xorg-x11*
             yum:
                     list: xorg-x11
           - name: remove xorg-x11
             yum:
                     name: xorg-x11*
                     state: absent
                 
