---
 - hosts: control
   become: true
   tasks:
           - name: ip forward disable
             sysctl:
                     name: net.ipv4.ip_forward
                     value: '0'
                     sysctl_set: yes
                     state: present
             register: name
           - name: output
             debug:
                   msg:
                           - ' {{ name }}' 
