---
 - hosts: control
   become: true
   tasks:
           - name: avahi service disable
             service:
                   name: avahi-daemon
                   state: stopped
                   enabled: false
           - name: cups service disable
             service:
                   name: cupsd
                   state: stopped
                   enabled: false
           - name: dhcpd service disable
             service:
                   name: dhcpd
                   state: stopped
                   enabled: false
           - name: Lapd service disable
             service:
                   name: slapd
                   state: stopped
                   enabled: false
           - name: NFS disable
             service:
                   name: nfs
                   state: stopped
                   enabled: false        
